name: Main
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0' # Every Sunday

jobs:
  main:
    runs-on: ${{ matrix.image }}
    timeout-minutes: 15
    strategy:
      matrix:
        image: [macos-12, ubuntu-22.04, windows-2022]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: "Cache downloads"
        uses: actions/cache@v4
        with:
          path: "build/download"
          key: ${{ hashFiles('gradle.properties') }}

      - name: Build
        run: ./gradlew build

      - name: 'Upload test results'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}.test-results
          path: build/reports/tests
        if: ${{ always() }}

      - name: 'Upload test logs'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}.test-logs
          path: build/idea-sandbox/system-test/log
        if: ${{ always() }}
